spring.application.name=CRM_Soporte_Tecnico

server.servlet.context-path=/sistema/api/v1

server.port=8080

spring.datasource.url=jdbc:postgresql://db-postgres:5432/crm_soporte_db
spring.datasource.username=crm_user
spring.datasource.password=crm_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.javax.persistence.validation.mode=none

spring.security.user.name=user
spring.security.user.password=password

jwt.keys.public-key-location=classpath:jwtKeys/public_key.pem
jwt.keys.private-key-location=classpath:jwtKeys/private_key.pem

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=crmserviciotecnico52@gmail.com
spring.mail.password=aatuckoiehczjcco
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true